version: 2

models:
  - name: dim_listings_cleansed
    description: "This is the cleansed listings table"
    columns:
      - name: listing_id
        description: "This is the unique id of the listing"
        tests:
          - unique
          - not_null
      - name: host_id
        description: "This is the unique id of the host, references the hosts table"
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: "This is the type of room"
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
  - name: mart_fullmoon_reveiws
    description: "This is the mart table for fullmoon reviews"
    columns:
      - name: is_fullmoon
        tests:
          - accepted_values:
              values: [1, 0]
  - name: fct_reviews
    description: "This is the fact table for reviews"
    columns:
      - name: review_id
        tests:
          - unique
          - not_null
